del *.tlog /f /s /q /a
del *.obj /f /s /q /a
del *.log /f /s /q /a
del *.pch /f /s /q /a
del *.idb /f /s /q /a
del *.pdb /f /s /q /a
del *.ilk /f /s /q /a
del *.sdf /f /s /q /a
del Project\x64\Debug\LOG\*.txt /f /s /q /a
